#!/bin/bash

# Fill your information here \/
ACCOUNT=''
PASSWORD=''
IDENTITY=''
KEY=''

success_message="Seu ponto foi efetivado :)"
error_message="Seu ponto não foi efetivado :("

function print_usage() {
  echo 'Usage: ahgora'
  echo ''
  echo 'optional arguments:'
  echo '    -n, --notify -> prints the output to system notifier'
  exit
}

while [ ! $# -eq 0 ]
do
  case "$1" in
    -n | --notify) notify_flag=true ;;
    *) print_usage
       exit 1 ;;
  esac
  shift
done

function printResponse() {
  local status=$1

  local red=$(tput bold)$(tput setaf 160)
  local green=$(tput bold)$(tput setaf 46)

  case "$status" in
    "error") echo -e ${red} $error_message;
             local message=$error_message ;;

    *)       echo -e ${green} $success_message;
             local message=$success_message ;;
  esac

  echo $(tput sgr0)
  echo ${CURL_FORM} | json_pp
  echo ""

  if [ $notify_flag ]; then
    notify-send "$message" "${CURL_FORM}"
  fi
}

function json_extract() {
  local key=$1
  local json=${CURL_FORM}

  local string_regex='"([^"\]|\\.)*"'
  local number_regex='-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][+-]?[0-9]+)?'
  local value_regex="${string_regex}|${number_regex}|true|false|null"
  local pair_regex="\"${key}\"[[:space:]]*:[[:space:]]*(${value_regex})"

  if [[ ${json} =~ ${pair_regex} ]]; then
    echo $(sed 's/^"\|"$//g' <<< "${BASH_REMATCH[1]}")
  else
    return 1
  fi
}

echo ""
echo ""

echo " ____        _                 _                           _          _ "
echo "|  _ \      | |               | |                         | |        | |"
echo "| |_) | __ _| |_ ___ _ __   __| | ___    _ __   ___  _ __ | |_ ___   | |"
echo "|  _ < / _  | __/ _ \ '_ \ / _  |/ _ \  | '_ \ / _ \| '_ \| __/ _ \  | |"
echo "| |_) | (_| | ||  __/ | | | (_| | (_) | | |_) | (_) | | | | || (_) | |_|"
echo "|____/ \__,_|\__\___|_| |_|\__,_|\___/  | .__/ \___/|_| |_|\__\___/  (_)"
echo "                                        | |                             "
echo "                                        |_|                             "

echo ""
echo ""

# Curl to the "api"
CURL_FORM=`curl -sX POST \
  -F "account=${ACCOUNT}" \
  -F "password=${PASSWORD}" \
  -F "identity=${IDENTITY}" \
  -F "origin=pw2" \
  -F "key=${KEY}" \
  http://www.ahgora.com.br/batidaonline/verifyIdentification`

result=`json_extract result`

if [ "${result}" == false ]
then
  printResponse "error"
  exit 3
else
  printResponse "success"
  exit 0
fi
